---
name: ArrayUtils
main: kim\present\lib\arrayutils\Loader
version: 4.1.0
api: [ 4.0.0 ]
authors: [ PresentKim, Blugin-team ]
description: Library that provides a method to fancy manipulate an array
...